services:
  postgres:
    image: postgres:16-alpine
    container_name: cc-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: cc
      POSTGRES_PASSWORD: cc
      POSTGRES_DB: ccdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  adminer:
    image: adminer:latest
    container_name: cc-adminer
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      ADMINER_DEFAULT_SERVER: postgres
    depends_on:
      - postgres

  backend:
    build: ../backend
    container_name: cc-backend
    restart: unless-stopped
    env_file:
      - ../backend/.env
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgresql://cc:cc@postgres:5432/ccdb
      ML_SVC_URL: http://ml-svc:8000

  ml-svc:
    build: ../ml-svc
    container_name: cc-mlsvc
    restart: unless-stopped
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
      args:
        VITE_API_BASE: "/api"
    container_name: cc-frontend
    depends_on:
      - backend
    ports:
      - "8081:8080"
    restart: unless-stopped

volumes:
  pgdata:
